FROM model-docker-env

RUN sudo apt-get install -y valgrind
RUN pip3 install --root-user-action=ignore filecheck lit
COPY home/create-ssh-user.sh docker-home/
COPY home/.zshrc docker-home/
RUN chmod -R o+r+w /docker-home
